### ISSUE TITLE
npm install / ci invocation should be optional when container starts

### ISSUE THREAD

**Issue by samtny** [digitalpulp/front-end#1]
When I up the box, I don't necessarily want to execute `npm install` right away.

Use case is I am a front-end architect running node commands on my local OSX environment. The built / compiled assets are shared into the container via nfs. Unfortunately if the container executes `npm install` for me, then conflicts may arise, such as the built version of `node-sass` is compiled with the wrong binary for my operating system by the container.

**Comment by FatherShawn** [comment]
It looks to me that this means removing all but the last conditional in `entrypoint.sh`
