### ISSUE TITLE
use nodenv / nvm instead of pinning node version inside the box

### ISSUE THREAD

**Issue by samtny** [digitalpulp/front-end#2]
improve maintainability / usability of the container by installing `nodenv` instead of a specific version of node.

use case is i am a front-end architect and wish to try out a new version of node - even a major version! - but cannot currently do so as the box is pinned at an older version.

tasks:

- do not install node, instead install nodenv and its companion build tool nodenv/node-build
- upon compilation invocation, first "cd" into the theme folder and run "nodenv install" from there. this will pick up whatever version of node is set there (various methods are used, most commonly the version is set in a ".node-version" file. if the node version already exists then this command will exit immediately. then run "npm i" (or npm ci, etc) from the same folder: the nodenv shim will pick up the command and execute it using the correct / currently set version of node.

**Comment by FatherShawn** [comment]
The first line of our Dockerfile shows that we've been extending a node based container (https://github.com/digitalpulp/front-end/blob/master/Dockerfile-codeship-10) from here: https://github.com/mhart/alpine-node  

It may be that someone is maintaining a nodenv container that we can use, or we may need to look at mhart's Dockerfiles for inspiration to see how we might build such a container.

**Comment by FatherShawn** [comment]
This looks promising: https://hub.docker.com/r/conchoid/docker-nodenv-builtins
